default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: graduate_exam_kadai_development
test:
  <<: *default
  database: graduate_exam_kadai_test
production:
  <<: *default
  database: graduate_exam_kadai_production
  username: graduate_exam_kadai
  password: <%= ENV['GRADUATE_EXAM_KADAI_DATABASE_PASSWORD'] %>
